In [20]:
import numpy as np
x = np.array([1,2]).reshape(2,1)
w = np.array([3,4]).reshape(2,1)

print(x[0]*w[0] + x[1]*w[1])
x
w

[11]


array([[3],
       [4]])

In [7]:
x*w

array([3, 8])

In [19]:
np.sum(x*w, axis = 1)

array([3, 8])