### Breast Cancer Dataset

In [1]:
from sklearn.datasets import load_breast_cancer
import numpy as np

breast_cancer = load_breast_cancer()
breast_cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [2]:
breast_cancer['data'].shape

(569, 30)

In [3]:
breast_cancer['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [4]:
breast_cancer['target_names']

array(['malignant', 'benign'], dtype='<U9')

### Use 30% of the data as labeled data

In [5]:
data, labels = breast_cancer.data[:,0:3], breast_cancer.target[:]

num_samples = len(labels)
shuffle_order = np.random.permutation(num_samples)

data = data[shuffle_order, :]
labels = labels[shuffle_order]

data = data / np.amax(data, axis = 0)
labels = labels / np.amax(labels, axis = 0)
data = data.astype('float32')
labels = labels.astype('float32')

In [6]:
print(data.shape)
print(data[0:5,:])
labels[0:5]

(569, 3)
[[0.4493063  0.52851325 0.43580902]
 [0.50836    0.42820773 0.4790451 ]
 [0.42511562 0.3808554  0.40970823]
 [0.38705087 0.39765784 0.37352785]
 [0.6833867  0.47275966 0.6657825 ]]


array([1., 1., 1., 1., 0.], dtype=float32)

In [7]:
X, y = data, labels

train_split = 0.6
n_train = int(train_split * num_samples)
x_train, y_train = X[:n_train], y[:n_train]
x_test, y_test = X[n_train:], y[n_train:]

y_train = y_train.reshape(y_train.shape[0],1)
y_test = y_test.reshape(y_test.shape[0],1)

In [8]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(341, 3)
(341, 1)
(228, 3)
(228, 1)


In [9]:
import tensorflow
import keras
from keras.models import Sequential
from keras.layers import Dense

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [10]:
model = Sequential()
model.add(Dense(8, activation='sigmoid', input_dim=3))
model.add(Dense(1, activation='linear'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 32        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(loss='mean_squared_error',optimizer='sgd')

In [12]:
import time
startTime = time.time()
model.fit(x_train,y_train,
         batch_size=4, epochs=200,
         verbose=1,
         validation_data=(x_test,y_test))

print('StartTime %0.3f ~ EndTime %0.3f , Duration %0.3f' %(startTime, time.time(), time.time() - startTime))

Train on 341 samples, validate on 228 samples
Epoch 1/200
341/341 [==============================] - 55s 162ms/step - loss: 0.2260 - val_loss: 0.2207
Epoch 2/200
341/341 [==============================] - 0s 677us/step - loss: 0.2245 - val_loss: 0.2159
Epoch 3/200
341/341 [==============================] - 0s 645us/step - loss: 0.2198 - val_loss: 0.2147
Epoch 4/200
341/341 [==============================] - 0s 628us/step - loss: 0.2184 - val_loss: 0.2117
Epoch 5/200
341/341 [==============================] - 0s 636us/step - loss: 0.2167 - val_loss: 0.2094
Epoch 6/200
341/341 [==============================] - 0s 636us/step - loss: 0.2145 - val_loss: 0.2078
Epoch 7/200
341/341 [==============================] - 0s 672us/step - loss: 0.2126 - val_loss: 0.2086
Epoch 8/200
341/341 [==============================] - 0s 666us/step - loss: 0.2102 - val_loss: 0.2036
Epoch 9/200
341/341 [==============================] - 0s 628us/step - loss: 0.2077 - val_loss: 0.2024
Epoch 10/200
341/341 [====

### A larger network with more data, more layers, more neurons and more epochs

In [13]:
data, labels = breast_cancer.data[:,:], breast_cancer.target[:]

num_samples = len(labels)
shuffle_order = np.random.permutation(num_samples)

data = data[shuffle_order, :]
labels = labels[shuffle_order]

data = data / np.amax(data, axis = 0)
labels = labels / np.amax(labels, axis = 0)
data = data.astype('float32')
labels = labels.astype('float32')

print(data.shape)
print(data[0:5,:])
labels[0:5]

(569, 30)
[[0.7047314  0.56390023 0.6896552  0.5037985  0.6016524  0.29733643
  0.34653234 0.4720676  0.52039474 0.55367404 0.26390532 0.20818833
  0.26683348 0.20730358 0.20860906 0.13980797 0.08563131 0.28812274
  0.17175427 0.0669236  0.7580466  0.6233347  0.7436306  0.5637047
  0.6792453  0.29773158 0.42907348 0.82061857 0.41699308 0.36698794]
 [0.40270367 0.6894094  0.38068965 0.15821671 0.42123622 0.11039375
  0.03826148 0.01553181 0.61480266 0.57758623 0.04211625 0.18274309
  0.04818016 0.01587053 0.11734661 0.12163959 0.04123737 0.05919682
  0.19468018 0.06876676 0.33518314 0.6812677  0.31775478 0.10632346
  0.41343215 0.13534972 0.08698083 0.07158075 0.42919555 0.34154215]
 [0.40234792 0.48472506 0.38090184 0.15757696 0.4981028  0.13610306
  0.08690253 0.11083499 0.4986842  0.5815887  0.09491821 0.19301945
  0.083303   0.03347473 0.29816896 0.068065   0.05209596 0.16982383
  0.27650413 0.07191689 0.34211987 0.48122728 0.31050956 0.10970851
  0.5795148  0.08646503 0.11533546 0.

array([0., 1., 1., 1., 0.], dtype=float32)

In [14]:
X, y = data, labels

train_split = 0.6
n_train = int(train_split * num_samples)
x_train, y_train = X[:n_train], y[:n_train]
x_test, y_test = X[n_train:], y[n_train:]

In [15]:
model4 = Sequential()
model4.add(Dense(16, activation='sigmoid', input_dim=30))
model4.add(Dense(16, activation='sigmoid'))
model4.add(Dense(1, activation='linear'))
model4.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 16)                496       
_________________________________________________________________
dense_4 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 17        
Total params: 785
Trainable params: 785
Non-trainable params: 0
_________________________________________________________________


228/228 [==============================] - 0s 39us/step

0.062496209582477286

StartTime 1531469181.153 ~ EndTime 1531469416.476 , Duration 235.323

In [16]:
import time
startTime = time.time()

model4.compile(loss='mean_squared_error',optimizer='sgd')
model4.fit(x_train,y_train,
         batch_size=4, epochs=1000,
         verbose=1,
         validation_data=(x_test,y_test))
score4 = model4.evaluate(x_test, y_test)
print(score4)

endTime = time.time()
print('StartTime %0.3f ~ EndTime %0.3f , Duration %0.3f' %(startTime, endTime, endTime - startTime))

Train on 341 samples, validate on 228 samples
Epoch 1/1000
341/341 [==============================] - 0s 1ms/step - loss: 0.3729 - val_loss: 0.2462
Epoch 2/1000
341/341 [==============================] - 0s 707us/step - loss: 0.2426 - val_loss: 0.2347
Epoch 3/1000
341/341 [==============================] - 0s 718us/step - loss: 0.2407 - val_loss: 0.2332
Epoch 4/1000
341/341 [==============================] - 0s 730us/step - loss: 0.2397 - val_loss: 0.2326
Epoch 5/1000
341/341 [==============================] - 0s 748us/step - loss: 0.2338 - val_loss: 0.2344
Epoch 6/1000
341/341 [==============================] - 0s 707us/step - loss: 0.2361 - val_loss: 0.2380
Epoch 7/1000
341/341 [==============================] - 0s 716us/step - loss: 0.2324 - val_loss: 0.2345
Epoch 8/1000
341/341 [==============================] - 0s 742us/step - loss: 0.2349 - val_loss: 0.2255
Epoch 9/1000
341/341 [==============================] - 0s 733us/step - loss: 0.2304 - val_loss: 0.2246
Epoch 10/1000
341/34