In [1]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
data, labels = iris.data[:, 0:3], iris.data[:,3]

num_samples = len(labels)
shuffle_order = np.random.permutation(num_samples)

data = data[shuffle_order,:]
labels = labels[shuffle_order]

data = data / np.amax(data, axis = 0)
labels = labels / np.amax(labels, axis = 0)
data = data.astype('float32')
labels = labels.astype("float32")

In [2]:
print(data.shape)
print(data[0:5,:])
labels[0:5]

(150, 3)
[[0.73417723 0.6136364  0.5942029 ]
 [0.5443038  0.6818182  0.1594203 ]
 [0.721519   0.6363636  0.65217394]
 [0.7721519  0.6818182  0.71014494]
 [0.7848101  0.77272725 0.7826087 ]]


array([0.4 , 0.04, 0.52, 0.72, 0.92], dtype=float32)

In [3]:
X, y = data, labels

test_split = 0.3
n_test = int(test_split * num_samples)
x_test, y_test = X[:n_test, :], y[:n_test]
x_train, y_train = X[n_test:, :], y[n_test:]

In [4]:
import tensorflow
import keras
from keras.models import Sequential
from keras.layers import Dense

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [6]:
model = Sequential()
model.add(Dense(8,activation='sigmoid', input_dim=3))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 32        
Total params: 32
Trainable params: 32
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.add(Dense(1, activation='linear'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 32        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile(loss='mean_squared_error', optimizer='sgd')

In [12]:
model.fit(x_train, y_train,
         batch_size=4, epochs=200,
         verbose=1,
         validation_data=(x_test,y_test))

Train on 105 samples, validate on 45 samples
Epoch 1/200
105/105 [==============================] - 0s 295us/step - loss: 0.0069 - val_loss: 0.0067
Epoch 2/200
105/105 [==============================] - 0s 295us/step - loss: 0.0070 - val_loss: 0.0071
Epoch 3/200
105/105 [==============================] - 0s 314us/step - loss: 0.0070 - val_loss: 0.0065
Epoch 4/200
105/105 [==============================] - 0s 304us/step - loss: 0.0069 - val_loss: 0.0070
Epoch 5/200
105/105 [==============================] - 0s 323us/step - loss: 0.0069 - val_loss: 0.0067
Epoch 6/200
105/105 [==============================] - 0s 314us/step - loss: 0.0069 - val_loss: 0.0065
Epoch 7/200
105/105 [==============================] - 0s 314us/step - loss: 0.0069 - val_loss: 0.0065
Epoch 8/200
105/105 [==============================] - 0s 362us/step - loss: 0.0069 - val_loss: 0.0067
Epoch 9/200
105/105 [==============================] - 0s 343us/step - loss: 0.0068 - val_loss: 0.0065
Epoch 10/200
105/105 [======

In [13]:
score = model.evaluate(x_test, y_test)

45/45 [==============================] - 0s 67us/step


In [15]:
print(score)

0.006343867350369692


In [16]:
y_pred = model.predict(x_test)

In [21]:
for yp,ya in list(zip(y_pred,y_test))[0:10]:
    print("predicted %0.3f, actual %0.3f"%(yp,ya))

predicted 0.535, actual 0.400
predicted 0.014, actual 0.040
predicted 0.603, actual 0.520
predicted 0.672, actual 0.720
predicted 0.757, actual 0.920
predicted 0.658, actual 0.720
predicted 0.065, actual 0.160
predicted 0.802, actual 0.920
predicted 0.706, actual 0.800
predicted 0.891, actual 0.720
